Feat(mailer): add support for dynamic template data
platanus/send_grid_mailer pull request #19
Opened 2020-09-03 23:44 UTC by imarquezc

In this pull request I updated `send_grid_mailer` in order to support dynamic templates data.

This was only possible upgrading sendgrid-ruby gem to `5.3.0`

This is [the PR](https://github.com/sendgrid/sendgrid-ruby/pull/300/files) where the feature was added.

Also, the api v5+ of sendgrid introduced some breaking changes [check the list here](https://github.com/sendgrid/sendgrid-ruby/blob/main/CHANGELOG.md). This PR also fixes those changes.

Finally small updates were made to the tests because of the changes.

2020-09-03 23:44 UTC, monkeyci reviewed
Some files could not be reviewed due to errors:
<details>
<summary>.rubocop.yml: Style/FileName has the wrong namespace - should be Naming</summary>
<pre>.rubocop.yml: Style/FileName has the wrong namespace - should be Naming
.rubocop.yml: Style/MethodName has the wrong namespace - should be Naming
.rubocop.yml: Style/PredicateName has the wrong namespace - should be Naming
.rubocop.yml: Style/VariableName has the wrong namespace - should be Naming
.rubocop.yml: Lint/EndAlignment has the wrong namespace - should be Layout
.rubocop.yml: Lint/DefEndAlignment has the wrong namespace - should be Layout
.rubocop.yml: Style/AccessorMethodName has the wrong namespace - should be Naming
.rubocop.yml: Style/AsciiIdentifiers has the wrong namespace - should be Naming
.rubocop.yml: Style/ClassAndModuleCamelCase has the wrong namespace - should be Naming
.rubocop.yml: Style/ConstantName has the wrong namespace - should be Naming
.rubocop.yml: Style/FlipFlop has the wrong namespace - should be Lint
.rubocop.yml: Lint/BlockAlignment has the wrong namespace - should be Layout
.rubocop.yml: Lint/ConditionPosition has the wrong namespace - should be Layout
Error: The `Style/TrailingCommaInLiteral` cop no longer exists. Please use `Style/TrailingCommaInArrayLiteral` and/or `Style/TrailingCommaInHashLiteral` instead.
(obsolete configuration found in .rubocop.yml, please update it)
The `Lint/InvalidCharacterLiteral` cop has been removed since it was never being actually triggered.
The `Style/OpMethod` cop has been renamed and moved to `Naming/BinaryOperatorParameterName`.
obsolete parameter EnforcedStyle (for Style/Encoding) found in .rubocop.yml
Style/Encoding no longer supports styles. The "never" behavior is always assumed.
obsolete parameter SupportedStyles (for Style/Encoding) found in .rubocop.yml
obsolete parameter MaxLineLength (for Style/IfUnlessModifier) found in .rubocop.yml
`Style/IfUnlessModifier: MaxLineLength` has been removed. Use `Metrics/LineLength: Max` instead
obsolete parameter MaxLineLength (for Style/WhileUntilModifier) found in .rubocop.yml
`Style/WhileUntilModifier: MaxLineLength` has been removed. Use `Metrics/LineLength: Max` instead
</pre>
</details>

2020-09-03 23:46 UTC, monkeyci reviewed
Some files could not be reviewed due to errors:
<details>
<summary>.rubocop.yml: Style/FileName has the wrong namespace - should be Naming</summary>
<pre>.rubocop.yml: Style/FileName has the wrong namespace - should be Naming
.rubocop.yml: Style/MethodName has the wrong namespace - should be Naming
.rubocop.yml: Style/PredicateName has the wrong namespace - should be Naming
.rubocop.yml: Style/VariableName has the wrong namespace - should be Naming
.rubocop.yml: Lint/EndAlignment has the wrong namespace - should be Layout
.rubocop.yml: Lint/DefEndAlignment has the wrong namespace - should be Layout
.rubocop.yml: Style/AccessorMethodName has the wrong namespace - should be Naming
.rubocop.yml: Style/AsciiIdentifiers has the wrong namespace - should be Naming
.rubocop.yml: Style/ClassAndModuleCamelCase has the wrong namespace - should be Naming
.rubocop.yml: Style/ConstantName has the wrong namespace - should be Naming
.rubocop.yml: Style/FlipFlop has the wrong namespace - should be Lint
.rubocop.yml: Lint/BlockAlignment has the wrong namespace - should be Layout
.rubocop.yml: Lint/ConditionPosition has the wrong namespace - should be Layout
Error: The `Style/TrailingCommaInLiteral` cop no longer exists. Please use `Style/TrailingCommaInArrayLiteral` and/or `Style/TrailingCommaInHashLiteral` instead.
(obsolete configuration found in .rubocop.yml, please update it)
The `Lint/InvalidCharacterLiteral` cop has been removed since it was never being actually triggered.
The `Style/OpMethod` cop has been renamed and moved to `Naming/BinaryOperatorParameterName`.
obsolete parameter EnforcedStyle (for Style/Encoding) found in .rubocop.yml
Style/Encoding no longer supports styles. The "never" behavior is always assumed.
obsolete parameter SupportedStyles (for Style/Encoding) found in .rubocop.yml
obsolete parameter MaxLineLength (for Style/IfUnlessModifier) found in .rubocop.yml
`Style/IfUnlessModifier: MaxLineLength` has been removed. Use `Metrics/LineLength: Max` instead
obsolete parameter MaxLineLength (for Style/WhileUntilModifier) found in .rubocop.yml
`Style/WhileUntilModifier: MaxLineLength` has been removed. Use `Metrics/LineLength: Max` instead
</pre>
</details>

2020-09-04 15:57 UTC, monkeyci reviewed
Some files could not be reviewed due to errors:
<details>
<summary>.rubocop.yml: Style/FileName has the wrong namespace - should be Naming</summary>
<pre>.rubocop.yml: Style/FileName has the wrong namespace - should be Naming
.rubocop.yml: Style/MethodName has the wrong namespace - should be Naming
.rubocop.yml: Style/PredicateName has the wrong namespace - should be Naming
.rubocop.yml: Style/VariableName has the wrong namespace - should be Naming
.rubocop.yml: Lint/EndAlignment has the wrong namespace - should be Layout
.rubocop.yml: Lint/DefEndAlignment has the wrong namespace - should be Layout
.rubocop.yml: Style/AccessorMethodName has the wrong namespace - should be Naming
.rubocop.yml: Style/AsciiIdentifiers has the wrong namespace - should be Naming
.rubocop.yml: Style/ClassAndModuleCamelCase has the wrong namespace - should be Naming
.rubocop.yml: Style/ConstantName has the wrong namespace - should be Naming
.rubocop.yml: Style/FlipFlop has the wrong namespace - should be Lint
.rubocop.yml: Lint/BlockAlignment has the wrong namespace - should be Layout
.rubocop.yml: Lint/ConditionPosition has the wrong namespace - should be Layout
Error: The `Style/TrailingCommaInLiteral` cop no longer exists. Please use `Style/TrailingCommaInArrayLiteral` and/or `Style/TrailingCommaInHashLiteral` instead.
(obsolete configuration found in .rubocop.yml, please update it)
The `Lint/InvalidCharacterLiteral` cop has been removed since it was never being actually triggered.
The `Style/OpMethod` cop has been renamed and moved to `Naming/BinaryOperatorParameterName`.
obsolete parameter EnforcedStyle (for Style/Encoding) found in .rubocop.yml
Style/Encoding no longer supports styles. The "never" behavior is always assumed.
obsolete parameter SupportedStyles (for Style/Encoding) found in .rubocop.yml
obsolete parameter MaxLineLength (for Style/IfUnlessModifier) found in .rubocop.yml
`Style/IfUnlessModifier: MaxLineLength` has been removed. Use `Metrics/LineLength: Max` instead
obsolete parameter MaxLineLength (for Style/WhileUntilModifier) found in .rubocop.yml
`Style/WhileUntilModifier: MaxLineLength` has been removed. Use `Metrics/LineLength: Max` instead
</pre>
</details>

2020-09-04 15:57 UTC, monkeyci commented on spec/dummy/app/assets/config/manifest.js
> +//= link_directory ../stylesheets .css
Expected space or tab after '//' in comment      spaced-comment<br>Newline required at end of file but not found    eol-last

2020-09-04 15:57 UTC, monkeyci commented on spec/dummy/app/assets/config/manifest.js
> +//= link_directory ../javascripts .js
Expected space or tab after '//' in comment      spaced-comment

2020-09-04 16:19 UTC, monkeyci commented on spec/dummy/spec/lib/send_grid_mailer/definition_spec.rb
> +      expect(personalization.dynamic_template_data).to eq({ key: 'value', other_key: 'other_value' })
Redundant curly braces around a hash parameter.<br>Line is too long. [101/100]

2020-09-04 16:19 UTC, monkeyci commented on spec/dummy/spec/lib/send_grid_mailer/definition_spec.rb
> +      subject.dynamic_template_data({ other_key: 'other_value' })
Name your test subject if you need to reference it explicitly.<br>Redundant curly braces around a hash parameter.

2020-09-04 16:19 UTC, monkeyci commented on spec/dummy/spec/lib/send_grid_mailer/definition_spec.rb
> +      subject.dynamic_template_data({ other_key: 'other_value' })
Name your test subject if you need to reference it explicitly.<br>Redundant curly braces around a hash parameter.

2020-09-04 16:19 UTC, monkeyci commented on spec/dummy/spec/lib/send_grid_mailer/definition_spec.rb
> +      expect(@substitution).to eq({ key: 'value' })
Replace instance variable with local variable or let.<br>Redundant curly braces around a hash parameter.

2020-09-04 16:19 UTC, monkeyci commented on spec/dummy/spec/lib/send_grid_mailer/definition_spec.rb
> +      @substitution = subject.dynamic_template_data({ key: 'value' })
Name your test subject if you need to reference it explicitly.<br>Redundant curly braces around a hash parameter.

2020-09-04 16:19 UTC, monkeyci commented on spec/dummy/spec/lib/send_grid_mailer/definition_spec.rb
> +      expect(@substitution).to eq("%subject%" => "Hi!")
Replace instance variable with local variable or let.

2020-11-17 14:42 UTC, monkeyci commented on spec/dummy/spec/lib/send_grid_mailer/definition_spec.rb
> +      subject.add_category("category2")
Name your test subject if you need to reference it explicitly.

2020-11-17 14:42 UTC, monkeyci commented on spec/dummy/spec/lib/send_grid_mailer/definition_spec.rb
> +      subject.add_category("category1")
Name your test subject if you need to reference it explicitly.

2021-01-08 17:24 UTC, difernandez requested changes
Sorry for the slow review, but thanks for the PR, support for dynamic templates is a very welcome addition 🎉 ! I haven't yet been able to test the feature though, so I'll update my review when I do.

There's just one thing I could find that should be looked into.

#21 adds support for dev environment, after merging that into this branch and fixing the issue I mentioned, I think this would be ready for merging into master!

2021-01-19 15:30 UTC, difernandez commented
I tested it, including the related PR #21, and it all seems to be working well! When the other PR and this one are ready, I'll approve and merge 🚀

2021-06-24 14:00 UTC, difernandez approved these changes
The CI problem will be checked at a later date, we'll merge this for now. Thanks again for your contribution!

2021-06-24 14:51 UTC, merged